### ISSUE TITLE
copy /b nw.exe+app.nw app.exe后出来的exe文件执行报错

### ISSUE THREAD

**Issue by sunlianlong** [Dn9x/A-Webkit#2]
不知道该项目还回复不，新手有个问题咨询一下，使用nw F:\github\a-webkit\app后可以看到页面正常引用index.html的同级目录下的css、js文件，但是copy /b nw.exe+app.nw app.exe后生成的exe文件运行提示的还是nw.exe执行的界面，将app.nw拖拽到nw.exe上提示Cannot extract package 
Failed to unzip the package file: E:\nwjs-v0.12.3-win-ia32\app.nw         不知道您是否知道这个是什么问题，测试仅将index.html和package.json文件压缩后执行打包就可以显示出来？

node-webkit版本：nwjs-v0.12.3-win-ia32

**Comment by Dn9x** [comment]
@sunlianlong 

这个还真不好解答，这个demo也很久了，你可以自行看最新的官方文档，
不知道你是学习还是实际开发使用，如果实际使用可以了解下这个：https://github.com/electron/electron

我中间有用过这个，这个的更新和完善要好很多。
